package org.strasa.middleware.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.strasa.middleware.model.StudyData;
import org.strasa.middleware.model.StudyDataExample;

public interface StudyDataMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studydata
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	@SelectProvider(type = StudyDataSqlProvider.class, method = "countByExample")
	int countByExample(StudyDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studydata
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	@DeleteProvider(type = StudyDataSqlProvider.class, method = "deleteByExample")
	int deleteByExample(StudyDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studydata
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	@Delete({ "delete from studydata", "where id = #{id,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studydata
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	@Insert({ "insert into studydata (id, studyid, ", "datarow, datacolumn, ",
			"datavalue)",
			"values (#{id,jdbcType=INTEGER}, #{studyid,jdbcType=INTEGER}, ",
			"#{datarow,jdbcType=INTEGER}, #{datacolumn,jdbcType=VARCHAR}, ",
			"#{datavalue,jdbcType=VARCHAR})" })
	int insert(StudyData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studydata
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	@InsertProvider(type = StudyDataSqlProvider.class, method = "insertSelective")
	int insertSelective(StudyData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studydata
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	@SelectProvider(type = StudyDataSqlProvider.class, method = "selectByExample")
	@Results({
			@Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "studyid", property = "studyid", jdbcType = JdbcType.INTEGER),
			@Result(column = "datarow", property = "datarow", jdbcType = JdbcType.INTEGER),
			@Result(column = "datacolumn", property = "datacolumn", jdbcType = JdbcType.VARCHAR),
			@Result(column = "datavalue", property = "datavalue", jdbcType = JdbcType.VARCHAR) })
	List<StudyData> selectByExample(StudyDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studydata
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	@Select({ "select", "id, studyid, datarow, datacolumn, datavalue",
			"from studydata", "where id = #{id,jdbcType=INTEGER}" })
	@Results({
			@Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "studyid", property = "studyid", jdbcType = JdbcType.INTEGER),
			@Result(column = "datarow", property = "datarow", jdbcType = JdbcType.INTEGER),
			@Result(column = "datacolumn", property = "datacolumn", jdbcType = JdbcType.VARCHAR),
			@Result(column = "datavalue", property = "datavalue", jdbcType = JdbcType.VARCHAR) })
	StudyData selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studydata
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	@UpdateProvider(type = StudyDataSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") StudyData record,
			@Param("example") StudyDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studydata
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	@UpdateProvider(type = StudyDataSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") StudyData record,
			@Param("example") StudyDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studydata
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	@UpdateProvider(type = StudyDataSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(StudyData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studydata
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	@Update({ "update studydata", "set studyid = #{studyid,jdbcType=INTEGER},",
			"datarow = #{datarow,jdbcType=INTEGER},",
			"datacolumn = #{datacolumn,jdbcType=VARCHAR},",
			"datavalue = #{datavalue,jdbcType=VARCHAR}",
			"where id = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKey(StudyData record);
}