package org.strasa.middleware.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.strasa.middleware.model.Study;
import org.strasa.middleware.model.StudyExample;
import org.apache.ibatis.annotations.SelectKey;

public interface StudyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table study
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	@SelectProvider(type = StudySqlProvider.class, method = "countByExample")
	int countByExample(StudyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table study
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	@DeleteProvider(type = StudySqlProvider.class, method = "deleteByExample")
	int deleteByExample(StudyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table study
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	@Delete({ "delete from study", "where id = #{id,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table study
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	@Insert({ "insert into study (studyname)",
			"values (#{studyname,jdbcType=VARCHAR})" })
	@SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Integer.class)
	@Options(useGeneratedKeys = true, keyProperty = "id")
	int insert(Study record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table study
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	@InsertProvider(type = StudySqlProvider.class, method = "insertSelective")
	@SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Integer.class)
	@Options(useGeneratedKeys = true, keyProperty = "id")
	int insertSelective(Study record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table study
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	@SelectProvider(type = StudySqlProvider.class, method = "selectByExample")
	@Results({
			@Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "studyname", property = "studyname", jdbcType = JdbcType.VARCHAR) })
	List<Study> selectByExample(StudyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table study
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	@Select({ "select", "id, studyname", "from study",
			"where id = #{id,jdbcType=INTEGER}" })
	@Results({
			@Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "studyname", property = "studyname", jdbcType = JdbcType.VARCHAR) })
	Study selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table study
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	@UpdateProvider(type = StudySqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") Study record,
			@Param("example") StudyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table study
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	@UpdateProvider(type = StudySqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") Study record,
			@Param("example") StudyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table study
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	@UpdateProvider(type = StudySqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(Study record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table study
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	@Update({ "update study", "set studyname = #{studyname,jdbcType=VARCHAR}",
			"where id = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKey(Study record);
}