package org.strasa.middleware.model;

public class Study {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study.id
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study.studyname
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	private String studyname;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study.id
	 * @return  the value of study.id
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study.id
	 * @param id  the value for study.id
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study.studyname
	 * @return  the value of study.studyname
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	public String getStudyname() {
		return studyname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study.studyname
	 * @param studyname  the value for study.studyname
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	public void setStudyname(String studyname) {
		this.studyname = studyname;
	}
}