package org.strasa.middleware.model;

public class StudyData {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studydata.id
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studydata.studyid
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	private Integer studyid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studydata.datarow
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	private Integer datarow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studydata.datacolumn
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	private String datacolumn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studydata.datavalue
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	private String datavalue;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studydata.id
	 * @return  the value of studydata.id
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studydata.id
	 * @param id  the value for studydata.id
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studydata.studyid
	 * @return  the value of studydata.studyid
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	public Integer getStudyid() {
		return studyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studydata.studyid
	 * @param studyid  the value for studydata.studyid
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	public void setStudyid(Integer studyid) {
		this.studyid = studyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studydata.datarow
	 * @return  the value of studydata.datarow
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	public Integer getDatarow() {
		return datarow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studydata.datarow
	 * @param datarow  the value for studydata.datarow
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	public void setDatarow(Integer datarow) {
		this.datarow = datarow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studydata.datacolumn
	 * @return  the value of studydata.datacolumn
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	public String getDatacolumn() {
		return datacolumn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studydata.datacolumn
	 * @param datacolumn  the value for studydata.datacolumn
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	public void setDatacolumn(String datacolumn) {
		this.datacolumn = datacolumn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studydata.datavalue
	 * @return  the value of studydata.datavalue
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	public String getDatavalue() {
		return datavalue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studydata.datavalue
	 * @param datavalue  the value for studydata.datavalue
	 * @mbggenerated  Wed Sep 11 13:30:06 SGT 2013
	 */
	public void setDatavalue(String datavalue) {
		this.datavalue = datavalue;
	}
}